### ISSUE TITLE
Add lint check on PR

### ISSUE THREAD

**Issue by bathienle** [Cytomine-ULiege/pims#50]
# Description

A GitHub Action should be implemented to automatically run PyLint on pull requests targeting the `master` and `production` branches. This will ensure that code adheres to linting standards and helps maintain consistent code quality.

# Requirements

- The action should be triggered on pull requests to the `master` branch.
- The action should run PyLint across the codebase for Python files.
- The action should fail if the PyLint score is under 9.9.
- The PyLint configuration (.pylintrc) should be customizable to meet project requirements.
- The PyLint output should be included in the GitHub Action logs for easier debugging.

# Task

- [x] Create .github/workflows/code-quality.yaml file for the GitHub Action.
- [x] Configure the action to run on pull requests to `master`.
- [x] Add steps to set up the Python environment and install pylint.
- [x] Add PyLint output to the action logs for easier troubleshooting.
- [x] Add pylint configuration file (pylintrc)
- [ ] (Optional) Add a lint status badge to the README file
